"""
fetch_weather.py
----------------
Downloads daily weather data from the NASA POWER Community "Ag" API for the
configured district and saves it to ``data/raw/weather.csv``.

Features
--------
* Local JSON cache (``data/raw/weather_cache.json``) — avoids re-downloading
  date ranges already fetched.
* Graceful offline fallback: on network failure the script falls back to the
  existing cache (if available) or to synthetic data (if cache is absent).
* Converts NASA POWER sentinel value −999 to NaN.
* ``--dry-run`` flag prints the API URL without fetching.

Usage
-----
    python src/data/fetch_weather.py
    python src/data/fetch_weather.py --dry-run
    python src/data/fetch_weather.py --config config/config.yaml
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import requests

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from src.utils.config_loader import load_config
from src.utils.logger import get_logger

logger = get_logger(__name__)

_TIMEOUT_SECONDS = 120
_DISCLAIMER = (
    "# SYNTHETIC DATA — generated by generate_synthetic.py"
    " — NOT real observations\n"
)


# ---------------------------------------------------------------------------
# API helpers
# ---------------------------------------------------------------------------

def _build_url(cfg: dict) -> str:
    """Construct the NASA POWER API URL from config.

    Parameters
    ----------
    cfg: Parsed configuration dictionary.

    Returns
    -------
    str
        Full API request URL.
    """
    nasa = cfg["nasa_power"]
    sp   = cfg["study_period"]
    dist = cfg["district"]
    params_str = ",".join(nasa["parameters"])
    start = f"{sp['start_year']}0101"
    end   = f"{sp['end_year']}1231"
    url = (
        f"{nasa['base_url']}"
        f"?parameters={params_str}"
        f"&community={nasa['community']}"
        f"&longitude={dist['lon']}"
        f"&latitude={dist['lat']}"
        f"&start={start}"
        f"&end={end}"
        f"&format=JSON"
    )
    return url


def _sentinel_to_nan(df: pd.DataFrame, sentinel: float = -999.0) -> pd.DataFrame:
    """Replace NASA POWER sentinel values with NaN.

    Parameters
    ----------
    df:       DataFrame of weather observations.
    sentinel: Sentinel value to replace (default −999).

    Returns
    -------
    pd.DataFrame
        DataFrame with sentinel values replaced by NaN.
    """
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    df[numeric_cols] = df[numeric_cols].replace(sentinel, np.nan)
    return df


def _parse_power_response(payload: dict, parameters: list[str]) -> pd.DataFrame:
    """Convert NASA POWER JSON payload to a tidy daily DataFrame.

    Parameters
    ----------
    payload:    Parsed JSON response from the API.
    parameters: List of variable names to extract.

    Returns
    -------
    pd.DataFrame
        Columns: date (str YYYY-MM-DD) + one column per parameter.
    """
    properties = payload["properties"]["parameter"]
    # Each parameter key maps to {YYYYMMDD: value, ...}
    first_param = parameters[0]
    dates_raw = sorted(properties[first_param].keys())
    dates = [f"{d[:4]}-{d[4:6]}-{d[6:]}" for d in dates_raw]

    data: dict[str, list] = {"date": dates}
    for param in parameters:
        data[param] = [properties[param][d] for d in dates_raw]

    return pd.DataFrame(data)


# ---------------------------------------------------------------------------
# Cache helpers
# ---------------------------------------------------------------------------

def _load_cache(cache_path: Path) -> dict | None:
    """Load the local JSON cache if it exists.

    Parameters
    ----------
    cache_path: Path to the cache file.

    Returns
    -------
    dict or None
    """
    if cache_path.exists():
        try:
            with cache_path.open("r", encoding="utf-8") as fh:
                return json.load(fh)
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("Could not read weather cache (%s): %s", cache_path, exc)
    return None


def _save_cache(cache_path: Path, payload: dict) -> None:
    """Save the raw API response to the local JSON cache.

    Parameters
    ----------
    cache_path: Path to the cache file.
    payload:    Raw API response dict.
    """
    try:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        with cache_path.open("w", encoding="utf-8") as fh:
            json.dump(payload, fh)
        logger.info("NASA POWER response cached to %s", cache_path)
    except OSError as exc:
        logger.warning("Could not write weather cache: %s", exc)


# ---------------------------------------------------------------------------
# Fallback
# ---------------------------------------------------------------------------

def _fallback_to_synthetic(cfg: dict, out_path: Path) -> None:
    """Generate synthetic weather as a fallback and save to out_path.

    Parameters
    ----------
    cfg:      Parsed configuration dictionary.
    out_path: Target CSV path.
    """
    logger.warning(
        "Falling back to SYNTHETIC weather data. "
        "Results are NOT based on real observations."
    )
    # Import here to avoid circular dependency at module level
    from src.data.generate_synthetic import generate_weather  # noqa: PLC0415
    seed = cfg["models"]["random_seed"]
    rng  = np.random.default_rng(seed)
    generate_weather(cfg, rng, out_path.parent)


# ---------------------------------------------------------------------------
# Main fetch logic
# ---------------------------------------------------------------------------

def fetch_weather(
    cfg: dict,
    dry_run: bool = False,
) -> pd.DataFrame | None:
    """Fetch daily weather from NASA POWER or fall back to cache/synthetic.

    Parameters
    ----------
    cfg:     Parsed configuration dictionary.
    dry_run: If True, print the API URL and return without fetching.

    Returns
    -------
    pd.DataFrame or None
        Clean DataFrame written to ``data/raw/weather.csv``, or None on
        dry-run.
    """
    url         = _build_url(cfg)
    parameters  = cfg["nasa_power"]["parameters"]
    sentinel    = cfg["nasa_power"]["sentinel_value"]
    cache_path  = Path(cfg["data"]["weather_cache"])
    out_path    = Path(cfg["data"]["raw_dir"]) / "weather.csv"

    if dry_run:
        print(f"[DRY RUN] NASA POWER URL:\n{url}")
        return None

    payload: dict | None = None

    # ---- Try live API ---------------------------------------------------
    try:
        logger.info("Fetching NASA POWER data …")
        resp = requests.get(url, timeout=_TIMEOUT_SECONDS)
        resp.raise_for_status()
        payload = resp.json()
        _save_cache(cache_path, payload)
        logger.info("NASA POWER fetch successful.")
    except requests.RequestException as exc:
        logger.warning(
            "NASA POWER API request failed: %s. Attempting cache fallback.", exc
        )

    # ---- Cache fallback -------------------------------------------------
    if payload is None:
        payload = _load_cache(cache_path)
        if payload is not None:
            logger.info("Loaded weather data from local cache: %s", cache_path)

    # ---- Synthetic fallback ---------------------------------------------
    if payload is None:
        _fallback_to_synthetic(cfg, out_path)
        return pd.read_csv(out_path, comment="#")

    # ---- Parse and save -------------------------------------------------
    df = _parse_power_response(payload, parameters)
    df = _sentinel_to_nan(df, sentinel=float(sentinel))

    nan_counts = df.isna().sum()
    if nan_counts.any():
        logger.warning(
            "NaN counts after sentinel replacement:\n%s", nan_counts[nan_counts > 0]
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False)
    logger.info("Weather data saved to %s (%d rows)", out_path, len(df))
    return df


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Fetch daily NASA POWER weather data for the study district."
    )
    parser.add_argument(
        "--config", default=None,
        help="Path to config.yaml (default: config/config.yaml)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print the API URL without fetching data.",
    )
    args = parser.parse_args()
    cfg  = load_config(args.config)
    fetch_weather(cfg, dry_run=args.dry_run)
