# SYNTHETIC DATA MODULE — generates placeholder CSVs for development/testing.
# Output files are NOT real observations. See data/raw/README.txt for schemas.
"""
generate_synthetic.py
---------------------
Generates synthetic raw CSV files for all five data sources used by the
Water-Smart Crop Planner pipeline.

Each dataset is generated only if its ``use_synthetic`` flag is ``true`` in
``config/config.yaml``.  Real files for a given dataset are left untouched.

Usage
-----
    python src/data/generate_synthetic.py              # uses default config
    python src/data/generate_synthetic.py --config config/config.yaml

Output files (when flagged synthetic):
    data/raw/weather.csv
    data/raw/yield.csv
    data/raw/prices.csv
    data/raw/crop_water.csv
    data/raw/cost.csv
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

# Allow running as a script from the project root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from src.utils.config_loader import load_config
from src.utils.logger import get_logger

logger = get_logger(__name__)

_DISCLAIMER = (
    "# SYNTHETIC DATA — generated by generate_synthetic.py"
    " — NOT real observations\n"
)

# ---------------------------------------------------------------------------
# Crop-level reference tables (FAO-56 / TNAU approximations)
# ---------------------------------------------------------------------------

# Seasonal water requirements (mm/season) — FAO-56 approximations for Tamil Nadu
_CROP_WATER: dict[str, dict[str, float]] = {
    "paddy":      {"kharif": 1200, "rabi": 1100, "summer": 1300},
    "groundnut":  {"kharif":  500, "rabi":  450, "summer":  550},
    "sugarcane":  {"kharif": 1800, "rabi": 1800, "summer": 1800},
    "black_gram": {"kharif":  350, "rabi":  300, "summer":  380},
    "green_gram": {"kharif":  320, "rabi":  280, "summer":  360},
    "maize":      {"kharif":  500, "rabi":  450, "summer":  520},
    "ragi":       {"kharif":  400, "rabi":  350, "summer":  420},
}

_KC_MID: dict[str, float] = {
    "paddy": 1.20, "groundnut": 1.15, "sugarcane": 1.25,
    "black_gram": 1.05, "green_gram": 1.05, "maize": 1.20, "ragi": 1.10,
}

_GROWING_DAYS: dict[str, int] = {
    "paddy": 120, "groundnut": 110, "sugarcane": 365,
    "black_gram": 75, "green_gram": 70, "maize": 100, "ragi": 100,
}

# Base yield (kg/ha) per crop — realistic Tamil Nadu baselines
_BASE_YIELD: dict[str, float] = {
    "paddy": 3200, "groundnut": 1500, "sugarcane": 90000,
    "black_gram": 650, "green_gram": 600, "maize": 4500, "ragi": 2200,
}

# Yield noise coefficient (std as fraction of mean)
_YIELD_CV: dict[str, float] = {
    "paddy": 0.18, "groundnut": 0.22, "sugarcane": 0.12,
    "black_gram": 0.25, "green_gram": 0.25, "maize": 0.20, "ragi": 0.20,
}

# Base price (₹/quintal)
_BASE_PRICE: dict[str, float] = {
    "paddy": 1900, "groundnut": 5200, "sugarcane": 3200,
    "black_gram": 6500, "green_gram": 6200, "maize": 1700, "ragi": 2900,
}

# Base cost (₹/ha) per season type
_BASE_COST: dict[str, dict[str, float]] = {
    "paddy":      {"kharif": 38000, "rabi": 36000, "summer": 40000},
    "groundnut":  {"kharif": 25000, "rabi": 23000, "summer": 26000},
    "sugarcane":  {"kharif": 85000, "rabi": 85000, "summer": 85000},
    "black_gram": {"kharif": 18000, "rabi": 17000, "summer": 19000},
    "green_gram": {"kharif": 17000, "rabi": 16000, "summer": 18000},
    "maize":      {"kharif": 22000, "rabi": 21000, "summer": 23000},
    "ragi":       {"kharif": 20000, "rabi": 19000, "summer": 21000},
}

# Rainfall sensitivity of yield (kg/ha per 100 mm above/below seasonal mean)
_YIELD_RAIN_SENSITIVITY: dict[str, float] = {
    "paddy": 150, "groundnut": 80, "sugarcane": 60,
    "black_gram": 50, "green_gram": 50, "maize": 100, "ragi": 70,
}

# Seasonal rainfall parameters (mean_mm, std_mm)
_SEASONAL_RAINFALL: dict[str, tuple[float, float]] = {
    "kharif": (850, 150),
    "rabi":   (280,  80),
    "summer": (120,  50),
}


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _write_csv(df: pd.DataFrame, path: Path, disclaimer: bool = True) -> None:
    """Write DataFrame to CSV, prepending the synthetic-data disclaimer."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if disclaimer:
        with path.open("w", encoding="utf-8") as fh:
            fh.write(_DISCLAIMER)
            df.to_csv(fh, index=False)
    else:
        df.to_csv(path, index=False)
    logger.info("Wrote synthetic file: %s  (%d rows)", path, len(df))


# ---------------------------------------------------------------------------
# Individual generators
# ---------------------------------------------------------------------------

def generate_weather(
    cfg: dict,
    rng: np.random.Generator,
    out_dir: Path,
) -> None:
    """Generate daily weather data for 2010–2023.

    Parameters
    ----------
    cfg:   Parsed configuration dictionary.
    rng:   NumPy random generator (seeded).
    out_dir: Directory for raw output files.
    """
    start_year = cfg["study_period"]["start_year"]
    end_year   = cfg["study_period"]["end_year"]
    dates = pd.date_range(
        start=f"{start_year}-01-01",
        end=f"{end_year}-12-31",
        freq="D",
    )
    n = len(dates)

    # Day-of-year based rainfall seasonality (monsoon peak ~day 200)
    doy = dates.day_of_year.to_numpy()
    rain_base = (
        8.0 * np.exp(-((doy - 200) ** 2) / (2 * 50**2))
        + 1.5 * np.exp(-((doy - 300) ** 2) / (2 * 30**2))
    )
    rain = np.maximum(0, rain_base + rng.normal(0, 2, n))

    # Temperature seasonality (peak ~Apr, trough ~Jan)
    temp_base = 28 + 5 * np.sin(2 * np.pi * (doy - 90) / 365)
    tmax = temp_base + rng.normal(2, 1.5, n)
    tmin = temp_base - rng.normal(8, 1.5, n)

    df = pd.DataFrame({
        "date":               dates.strftime("%Y-%m-%d"),
        "PRECTOTCORR":        rain.round(2),
        "T2M_MAX":            tmax.round(2),
        "T2M_MIN":            tmin.round(2),
        "RH2M":               np.clip(rng.normal(70, 10, n), 20, 100).round(1),
        "WS2M":               np.clip(rng.normal(2.5, 0.8, n), 0.1, 12).round(2),
        "ALLSKY_SFC_SW_DWN":  np.clip(rng.normal(18, 4, n), 4, 30).round(2),
    })

    _write_csv(df, out_dir / "weather.csv")


def generate_yield(
    cfg: dict,
    rng: np.random.Generator,
    out_dir: Path,
) -> None:
    """Generate annual district-level yield data for all crops and seasons.

    Parameters
    ----------
    cfg:   Parsed configuration dictionary.
    rng:   NumPy random generator (seeded).
    out_dir: Directory for raw output files.
    """
    crops   = cfg["crops"]["candidates"]
    seasons = cfg["seasons"]
    years   = range(cfg["study_period"]["start_year"],
                    cfg["study_period"]["end_year"] + 1)
    records = []

    for year in years:
        for season in seasons:
            rain_mean, rain_std = _SEASONAL_RAINFALL[season]
            seasonal_rain = max(0, rng.normal(rain_mean, rain_std))

            for crop in crops:
                base   = _BASE_YIELD[crop]
                cv     = _YIELD_CV[crop]
                sens   = _YIELD_RAIN_SENSITIVITY[crop]
                rain_effect = sens * (seasonal_rain - rain_mean) / 100
                yield_val = max(
                    50,
                    base + rain_effect + rng.normal(0, base * cv),
                )
                records.append({
                    "year":         year,
                    "season":       season,
                    "crop":         crop,
                    "district":     "Tiruvallur",
                    "yield_kg_ha":  round(yield_val, 1),
                    "area_ha":      round(rng.uniform(1000, 15000), 0),
                    "source":       "synthetic",
                })

    df = pd.DataFrame(records)
    _write_csv(df, out_dir / "yield.csv")


def generate_prices(
    cfg: dict,
    rng: np.random.Generator,
    out_dir: Path,
) -> None:
    """Generate monthly wholesale price data for all crops and markets.

    Parameters
    ----------
    cfg:   Parsed configuration dictionary.
    rng:   NumPy random generator (seeded).
    out_dir: Directory for raw output files.
    """
    crops   = cfg["crops"]["candidates"]
    markets = cfg["data"].get("price_markets", ["Koyambedu", "Tiruvallur"])
    years   = range(cfg["study_period"]["start_year"],
                    cfg["study_period"]["end_year"] + 1)
    records = []

    for market in markets:
        for crop in crops:
            price = _BASE_PRICE[crop]
            for year in years:
                for month in range(1, 13):
                    # Random walk with slight upward drift (3 % p.a.)
                    price = max(100, price * (1 + rng.normal(0.0025, 0.04)))
                    records.append({
                        "year":               year,
                        "month":              month,
                        "crop":               crop,
                        "market":             market,
                        "price_inr_quintal":  round(price, 2),
                        "source":             "synthetic",
                    })

    df = pd.DataFrame(records)
    _write_csv(df, out_dir / "prices.csv")


def generate_crop_water(
    cfg: dict,
    out_dir: Path,
) -> None:
    """Generate crop water requirement lookup table.

    Parameters
    ----------
    cfg:   Parsed configuration dictionary.
    out_dir: Directory for raw output files.
    """
    crops   = cfg["crops"]["candidates"]
    seasons = cfg["seasons"]
    records = []

    for crop in crops:
        for season in seasons:
            records.append({
                "crop":         crop,
                "season":       season,
                "water_req_mm": _CROP_WATER[crop][season],
                "growing_days": _GROWING_DAYS[crop],
                "kc_mid":       _KC_MID[crop],
                "source":       "synthetic",
            })

    df = pd.DataFrame(records)
    _write_csv(df, out_dir / "crop_water.csv")


def generate_cost(
    cfg: dict,
    rng: np.random.Generator,
    out_dir: Path,
) -> None:
    """Generate annual cultivation cost data for all crops and seasons.

    Parameters
    ----------
    cfg:   Parsed configuration dictionary.
    rng:   NumPy random generator (seeded).
    out_dir: Directory for raw output files.
    """
    crops   = cfg["crops"]["candidates"]
    seasons = cfg["seasons"]
    years   = range(cfg["study_period"]["start_year"],
                    cfg["study_period"]["end_year"] + 1)
    records = []

    for crop in crops:
        for season in seasons:
            base_cost = _BASE_COST[crop][season]
            for year in years:
                # 5–7 % annual cost inflation
                inflation = 1 + rng.uniform(0.05, 0.07)
                base_cost = base_cost * inflation
                records.append({
                    "year":         year,
                    "season":       season,
                    "crop":         crop,
                    "cost_inr_ha":  round(base_cost, 0),
                    "source":       "synthetic",
                })

    df = pd.DataFrame(records)
    _write_csv(df, out_dir / "cost.csv")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def run(config_path: str | None = None) -> None:
    """Run the synthetic data generator for all datasets flagged in config.

    Parameters
    ----------
    config_path:
        Path to config YAML.  Defaults to ``config/config.yaml``.
    """
    cfg     = load_config(config_path)
    flags   = cfg["data"]["use_synthetic"]
    seed    = cfg["models"]["random_seed"]
    rng     = np.random.default_rng(seed)
    out_dir = Path(cfg["data"]["raw_dir"])

    generated: list[str] = []

    if flags.get("weather", False):
        generate_weather(cfg, rng, out_dir)
        generated.append("weather")

    if flags.get("yield", False):
        generate_yield(cfg, rng, out_dir)
        generated.append("yield")

    if flags.get("prices", False):
        generate_prices(cfg, rng, out_dir)
        generated.append("prices")

    if flags.get("crop_water", False):
        generate_crop_water(cfg, out_dir)
        generated.append("crop_water")

    if flags.get("cost", False):
        generate_cost(cfg, rng, out_dir)
        generated.append("cost")

    if generated:
        logger.info(
            "Synthetic data generation complete. Datasets: %s",
            ", ".join(generated),
        )
    else:
        logger.info(
            "No synthetic datasets requested (all use_synthetic flags are false)."
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate synthetic raw CSV files for the Water-Smart Crop Planner."
    )
    parser.add_argument(
        "--config",
        default=None,
        help="Path to config.yaml (default: config/config.yaml)",
    )
    args = parser.parse_args()
    run(args.config)
